# Generated by Django 3.1.5 on 2021-01-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PchStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('buy_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('average_buy_price', models.IntegerField(default=0)),
                ('average_sell_price', models.IntegerField(default=0)),
                ('net_buy', models.IntegerField(default=0)),
            ],
        ),
    ]
