# Generated by Django 3.1.5 on 2021-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCHStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('buy_price', models.CharField(max_length=255)),
                ('sell_price', models.CharField(max_length=255)),
                ('average_buy_price', models.CharField(max_length=255)),
                ('average_sell_price', models.CharField(max_length=255)),
                ('net_buy', models.CharField(max_length=255)),
                ('stock_date', models.DateField()),
                ('create_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
            ],
        ),
    ]
