# Generated by Django 3.1.5 on 2021-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pchstock',
            name='stock_date',
            field=models.CharField(max_length=255),
        ),
    ]
