# Generated by Django 3.1.5 on 2021-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0002_auto_20210128_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pchstock',
            name='update_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
