# Generated by Django 3.1.5 on 2021-02-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0003_auto_20210128_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pchstock',
            name='buy_price',
            field=models.IntegerField(null=True),
        )
    ]
