# Generated by Django 3.1.5 on 2021-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0005_auto_20210204_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pchstock',
            name='average_buy_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pchstock',
            name='average_sell_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pchstock',
            name='net_buy',
            field=models.IntegerField(null=True),
        ),
    ]
